### ISSUE TITLE
Missing instructions for integration with devise

### ISSUE THREAD

**Issue by melzreal** [dxw/mail-notify#28]
Context: Tried following the current README and kept hitting an error of  undefined method view_mail. The intent was using notify for sending emails of password resets.

After checking the repo of the owner that suggested the readme update for the devise integration, I found these two extra settings were needed to get this to work.

Couldn't submit a PR to update the README so here is the instruction update:

#### With Devise

If you're using [Devise](https://github.com/heartcombo/devise), you can overwrite your Devise mailer to use mail-notify for password reset emails etc.

In `app/mailers/application_mailer.rb` ensure your application mailer inherits from Mail::Notify

```ruby
class ApplicationMailer < Mail::Notify::Mailer
end
```

In `config/initializers/devise.rb`:

```ruby
config.mailer = 'DeviseMailer'
```

```ruby
config.parent_mailer = 'ApplicationMailer'
```

in `app/mailers/devise_mailer.rb`:

```ruby
class DeviseMailer < Devise::Mailer
  def devise_mail(record, action, opts = {}, &block)
    initialize_from_record(record)
    view_mail(ENV['NOTIFY_TEMPLATE_ID'], headers_for(action, opts))
  end
end
```

**Comment by mec** [comment]
@melzreal thanks so much for this - I wasn't sure if your suggestions had already been incorporated, but they have now!

We've moved the Devise instructions to the wiki as they are no a core part of the gem: https://github.com/dxw/mail-notify/wiki/Use-with-Devise

I am closing this now! 🎉 😄
