### ISSUE TITLE
Version 1.0.5 triggers uninitialized constant Mail::Notify error

### ISSUE THREAD

**Issue by vassyz** [dxw/mail-notify#61]
The build on our repo is failing on the dependabot PR for the update from 1.0.4.to 1.0.5 https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/2131. I will investigate further but I think you should be aware of this as it's a minor version and shouldn't be breaking things.

Spec error:
```
NameError:
  uninitialized constant Mail::Notify
# ./app/mailers/application_mailer.rb:1:in `<top (required)>'
```

Affected class:
```ruby
class ApplicationMailer < Mail::Notify::Mailer
```

**Comment by vassyz** [comment]
Adding a `require` statement fixes the issue. But I'm a bit confused why this happens when switching to `1.0.5`
```ruby
require "notify"

class ApplicationMailer < Mail::Notify::Mailer
```

**Comment by pezholio** [comment]
Apologies for this. The latest version (`1.1.0`) should fix this. More context in #63 if you're interested.
